// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: api/proto/trade/trade.proto

package tradepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_trade_trade_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_api_proto_trade_trade_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{0}
}

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_CURRENCY_BTC         Currency = 1
	Currency_CURRENCY_ETH         Currency = 2
	Currency_CURRENCY_USDT        Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_BTC",
		2: "CURRENCY_ETH",
		3: "CURRENCY_USDT",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_BTC":         1,
		"CURRENCY_ETH":         2,
		"CURRENCY_USDT":        3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_trade_trade_proto_enumTypes[1].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_api_proto_trade_trade_proto_enumTypes[1]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{1}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_trade_trade_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_api_proto_trade_trade_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN             OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 4
	OrderStatus_ORDER_STATUS_REJECTED         OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_OPEN",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELLED",
		5: "ORDER_STATUS_REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_OPEN":             1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELLED":        4,
		"ORDER_STATUS_REJECTED":         5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_trade_trade_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_proto_trade_trade_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{3}
}

type PlaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端生成的幂等键。同一个 user_id 下 request_id 必须唯一，
	// 即使交易组合或其他字段发生变化也不能复用。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 实验环境临时字段。后续接入认证时，会改为从凭证
	// 或网关注入的 metadata 中获取用户身份。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 当前版本只支持 BTC/USDT 和 ETH/USDT 两个交易组合。
	BaseCurrency  Currency  `protobuf:"varint,3,opt,name=base_currency,json=baseCurrency,proto3,enum=trade.Currency" json:"base_currency,omitempty"`
	QuoteCurrency Currency  `protobuf:"varint,4,opt,name=quote_currency,json=quoteCurrency,proto3,enum=trade.Currency" json:"quote_currency,omitempty"`
	Side          Side      `protobuf:"varint,5,opt,name=side,proto3,enum=trade.Side" json:"side,omitempty"`
	Type          OrderType `protobuf:"varint,6,opt,name=type,proto3,enum=trade.OrderType" json:"type,omitempty"`
	// 十进制字符串，例如 "42000.12"。限价单必填，市价单忽略。
	// 这里刻意避免使用二进制浮点数，防止金额精度丢失。
	LimitPrice string `protobuf:"bytes,7,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// 数字货币数量的十进制字符串，必须大于 0。
	Quantity      string `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetBaseCurrency() Currency {
	if x != nil {
		return x.BaseCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetQuoteCurrency() Currency {
	if x != nil {
		return x.QuoteCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetLimitPrice() string {
	if x != nil {
		return x.LimitPrice
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Fill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	MakerOrderId  string                 `protobuf:"bytes,2,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId  string                 `protobuf:"bytes,3,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExecutedAtMs  int64                  `protobuf:"varint,6,opt,name=executed_at_ms,json=executedAtMs,proto3" json:"executed_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{1}
}

func (x *Fill) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Fill) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *Fill) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *Fill) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Fill) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Fill) GetExecutedAtMs() int64 {
	if x != nil {
		return x.ExecutedAtMs
	}
	return 0
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency      Currency               `protobuf:"varint,4,opt,name=base_currency,json=baseCurrency,proto3,enum=trade.Currency" json:"base_currency,omitempty"`
	QuoteCurrency     Currency               `protobuf:"varint,5,opt,name=quote_currency,json=quoteCurrency,proto3,enum=trade.Currency" json:"quote_currency,omitempty"`
	Side              Side                   `protobuf:"varint,6,opt,name=side,proto3,enum=trade.Side" json:"side,omitempty"`
	Type              OrderType              `protobuf:"varint,7,opt,name=type,proto3,enum=trade.OrderType" json:"type,omitempty"`
	LimitPrice        string                 `protobuf:"bytes,8,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	OriginalQuantity  string                 `protobuf:"bytes,9,opt,name=original_quantity,json=originalQuantity,proto3" json:"original_quantity,omitempty"`
	ExecutedQuantity  string                 `protobuf:"bytes,10,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	RemainingQuantity string                 `protobuf:"bytes,11,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	Status            OrderStatus            `protobuf:"varint,12,opt,name=status,proto3,enum=trade.OrderStatus" json:"status,omitempty"`
	CreatedAtMs       int64                  `protobuf:"varint,13,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	UpdatedAtMs       int64                  `protobuf:"varint,14,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetBaseCurrency() Currency {
	if x != nil {
		return x.BaseCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *Order) GetQuoteCurrency() Currency {
	if x != nil {
		return x.QuoteCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetLimitPrice() string {
	if x != nil {
		return x.LimitPrice
	}
	return ""
}

func (x *Order) GetOriginalQuantity() string {
	if x != nil {
		return x.OriginalQuantity
	}
	return ""
}

func (x *Order) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *Order) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Order) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Fills         []*Fill                `protobuf:"bytes,2,rep,name=fills,proto3" json:"fills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PlaceOrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_trade_trade_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trade_trade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trade_trade_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_api_proto_trade_trade_proto protoreflect.FileDescriptor

const file_api_proto_trade_trade_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/trade/trade.proto\x12\x05trade\"\xbd\x02\n" +
	"\x11PlaceOrderRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\rbase_currency\x18\x03 \x01(\x0e2\x0f.trade.CurrencyR\fbaseCurrency\x126\n" +
	"\x0equote_currency\x18\x04 \x01(\x0e2\x0f.trade.CurrencyR\rquoteCurrency\x12\x1f\n" +
	"\x04side\x18\x05 \x01(\x0e2\v.trade.SideR\x04side\x12$\n" +
	"\x04type\x18\x06 \x01(\x0e2\x10.trade.OrderTypeR\x04type\x12\x1f\n" +
	"\vlimit_price\x18\a \x01(\tR\n" +
	"limitPrice\x12\x1a\n" +
	"\bquantity\x18\b \x01(\tR\bquantity\"\xc5\x01\n" +
	"\x04Fill\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12$\n" +
	"\x0emaker_order_id\x18\x02 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x03 \x01(\tR\ftakerOrderId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12$\n" +
	"\x0eexecuted_at_ms\x18\x06 \x01(\x03R\fexecutedAtMs\"\xad\x04\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\rbase_currency\x18\x04 \x01(\x0e2\x0f.trade.CurrencyR\fbaseCurrency\x126\n" +
	"\x0equote_currency\x18\x05 \x01(\x0e2\x0f.trade.CurrencyR\rquoteCurrency\x12\x1f\n" +
	"\x04side\x18\x06 \x01(\x0e2\v.trade.SideR\x04side\x12$\n" +
	"\x04type\x18\a \x01(\x0e2\x10.trade.OrderTypeR\x04type\x12\x1f\n" +
	"\vlimit_price\x18\b \x01(\tR\n" +
	"limitPrice\x12+\n" +
	"\x11original_quantity\x18\t \x01(\tR\x10originalQuantity\x12+\n" +
	"\x11executed_quantity\x18\n" +
	" \x01(\tR\x10executedQuantity\x12-\n" +
	"\x12remaining_quantity\x18\v \x01(\tR\x11remainingQuantity\x12*\n" +
	"\x06status\x18\f \x01(\x0e2\x12.trade.OrderStatusR\x06status\x12\"\n" +
	"\rcreated_at_ms\x18\r \x01(\x03R\vcreatedAtMs\x12\"\n" +
	"\rupdated_at_ms\x18\x0e \x01(\x03R\vupdatedAtMs\"[\n" +
	"\x12PlaceOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.trade.OrderR\x05order\x12!\n" +
	"\x05fills\x18\x02 \x03(\v2\v.trade.FillR\x05fills\"H\n" +
	"\x12CancelOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"9\n" +
	"\x13CancelOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.trade.OrderR\x05order\"E\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*[\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_BTC\x10\x01\x12\x10\n" +
	"\fCURRENCY_ETH\x10\x02\x12\x11\n" +
	"\rCURRENCY_USDT\x10\x03*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*\xb5\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x052\xcb\x01\n" +
	"\x0eTradingService\x12A\n" +
	"\n" +
	"PlaceOrder\x12\x18.trade.PlaceOrderRequest\x1a\x19.trade.PlaceOrderResponse\x12D\n" +
	"\vCancelOrder\x12\x19.trade.CancelOrderRequest\x1a\x1a.trade.CancelOrderResponse\x120\n" +
	"\bGetOrder\x12\x16.trade.GetOrderRequest\x1a\f.trade.OrderB#Z!orderbook/api/proto/trade;tradepbb\x06proto3"

var (
	file_api_proto_trade_trade_proto_rawDescOnce sync.Once
	file_api_proto_trade_trade_proto_rawDescData []byte
)

func file_api_proto_trade_trade_proto_rawDescGZIP() []byte {
	file_api_proto_trade_trade_proto_rawDescOnce.Do(func() {
		file_api_proto_trade_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_trade_trade_proto_rawDesc), len(file_api_proto_trade_trade_proto_rawDesc)))
	})
	return file_api_proto_trade_trade_proto_rawDescData
}

var file_api_proto_trade_trade_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_trade_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_trade_trade_proto_goTypes = []any{
	(Side)(0),                   // 0: trade.Side
	(Currency)(0),               // 1: trade.Currency
	(OrderType)(0),              // 2: trade.OrderType
	(OrderStatus)(0),            // 3: trade.OrderStatus
	(*PlaceOrderRequest)(nil),   // 4: trade.PlaceOrderRequest
	(*Fill)(nil),                // 5: trade.Fill
	(*Order)(nil),               // 6: trade.Order
	(*PlaceOrderResponse)(nil),  // 7: trade.PlaceOrderResponse
	(*CancelOrderRequest)(nil),  // 8: trade.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 9: trade.CancelOrderResponse
	(*GetOrderRequest)(nil),     // 10: trade.GetOrderRequest
}
var file_api_proto_trade_trade_proto_depIdxs = []int32{
	1,  // 0: trade.PlaceOrderRequest.base_currency:type_name -> trade.Currency
	1,  // 1: trade.PlaceOrderRequest.quote_currency:type_name -> trade.Currency
	0,  // 2: trade.PlaceOrderRequest.side:type_name -> trade.Side
	2,  // 3: trade.PlaceOrderRequest.type:type_name -> trade.OrderType
	1,  // 4: trade.Order.base_currency:type_name -> trade.Currency
	1,  // 5: trade.Order.quote_currency:type_name -> trade.Currency
	0,  // 6: trade.Order.side:type_name -> trade.Side
	2,  // 7: trade.Order.type:type_name -> trade.OrderType
	3,  // 8: trade.Order.status:type_name -> trade.OrderStatus
	6,  // 9: trade.PlaceOrderResponse.order:type_name -> trade.Order
	5,  // 10: trade.PlaceOrderResponse.fills:type_name -> trade.Fill
	6,  // 11: trade.CancelOrderResponse.order:type_name -> trade.Order
	4,  // 12: trade.TradingService.PlaceOrder:input_type -> trade.PlaceOrderRequest
	8,  // 13: trade.TradingService.CancelOrder:input_type -> trade.CancelOrderRequest
	10, // 14: trade.TradingService.GetOrder:input_type -> trade.GetOrderRequest
	7,  // 15: trade.TradingService.PlaceOrder:output_type -> trade.PlaceOrderResponse
	9,  // 16: trade.TradingService.CancelOrder:output_type -> trade.CancelOrderResponse
	6,  // 17: trade.TradingService.GetOrder:output_type -> trade.Order
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_trade_trade_proto_init() }
func file_api_proto_trade_trade_proto_init() {
	if File_api_proto_trade_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_trade_trade_proto_rawDesc), len(file_api_proto_trade_trade_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_trade_trade_proto_goTypes,
		DependencyIndexes: file_api_proto_trade_trade_proto_depIdxs,
		EnumInfos:         file_api_proto_trade_trade_proto_enumTypes,
		MessageInfos:      file_api_proto_trade_trade_proto_msgTypes,
	}.Build()
	File_api_proto_trade_trade_proto = out.File
	file_api_proto_trade_trade_proto_goTypes = nil
	file_api_proto_trade_trade_proto_depIdxs = nil
}
