apiVersion: v1
kind: Service
metadata:
  name: consul-server
  namespace: consul
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
    - name: server
      port: 8300
    - name: serf-tcp
      port: 8301
    - name: serf-udp
      port: 8301
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
spec:
  type: NodePort
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      nodePort: 30850
