apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server
  namespace: consul
spec:
  serviceName: consul-server
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: docker.io/hashicorp/consul:1.20.6
          command: ["consul", "agent", "-config-dir=/consul/config", "-bind=$(POD_IP)", "-advertise=$(POD_IP)"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8500
          volumeMounts:
            - name: config
              mountPath: /consul/config
            - name: data
              mountPath: /consul/data
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: consul-config
              - secret:
                  name: consul-gossip
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
